on:
  workflow_dispatch:
  push:

name: some-ruby-workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run some script that runs ruby code
      run: |
        docker run \
        -v ${PWD}:/mnt \
        ruby:3.1.1-alpine3.15 /bin/sh /mnt/run.sh
